ARG ARCH=
ARG MAKEFLAGS="-j$(nproc)"

ARG CUDA_VERSION=11.2.2
ARG CUDNN_VERSION=8
ARG CUDA_ARCH_BIN=8.6

FROM nvidia/cuda:${CUDA_VERSION}-cudnn${CUDNN_VERSION}-devel-ubuntu20.04
LABEL maintainer="Mario Cristovao <mjpc13@protonmail.com>"

ENV DEBIAN_FRONTEND=noninteractive


SHELL ["/bin/bash","-c"]

# Install required packages

RUN apt-get update && apt-get -y install build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev python-dev python3-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev

RUN apt install -y libeigen3-dev


# Install OpenCV Contribs
WORKDIR /opt
RUN git clone https://github.com/opencv/opencv_contrib.git
WORKDIR /opt/opencv_contrib/
RUN git checkout 4.5.1


#Install OpenCV version 4.5.1
WORKDIR /opt
RUN git clone https://github.com/opencv/opencv.git
WORKDIR /opt/opencv
RUN git checkout 4.5.1
WORKDIR /opt/opencv/build/

RUN cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=/app \
-D BUILD_EXAMPLES=OFF \
-D INSTALL_PYTHON_EXAMPLES=OFF \
-D INSTALL_C_EXAMPLES=OFF \
-D OPENCV_ENABLE_NONFREE=ON \
-D WITH_EIGEN=ON \
-D WITH_CUDA=ON \
-D WITH_CUDNN=ON \
-D OPENCV_DNN_CUDA=ON \
-D CUDA_ARCH_BIN=${CUDA_ARCH_BIN} \
-D WITH_CUBLAS=1 \
-D CUDA_FAST_MATH=ON \
-D ENABLE_FAST_MATH=1 \
-D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules/ \
-D HAVE_opencv_python2=ON \
-D HAVE_opencv_python3=ON \
-D BUILD_opencv_python2=ON \
-D BUILD_opencv_python3=ON \
-D BUILD_EXAMPLES=OFF ..

RUN make -j8 install


CMD ["bash"]
